RetinaFace:
    onnx_file:     "../retinaface_4.onnx"
    engine_file:   "../retinaface_4.engine"
    BATCH_SIZE:    4
    INPUT_CHANNEL: 3
    IMAGE_WIDTH:   640
    IMAGE_HEIGHT:  640
    obj_threshold: 0.5
    nms_threshold: 0.45
    detect_mask:   False
    mask_thresh:   0.5
    landmark_std:  1
    feature_steps: [32, 16, 8]
    anchor_sizes:  [[512, 256], [128, 64], [32, 16]]
